# Generated by Django 4.2.30 on 2026-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('landing_view', 'เปิดหน้าแรก'), ('dream_started', 'เริ่มวิเคราะห์ฝัน'), ('dream_completed', 'วิเคราะห์ฝันสำเร็จ'), ('formula_used', 'ใช้เครื่องคำนวณสูตร'), ('news_opened', 'เปิดอ่านข่าว'), ('number_saved', 'บันทึกเลขลงสมุด'), ('result_checked', 'ตรวจผลหวย'), ('history_viewed', 'ดูประวัติ'), ('share_used', 'แชร์/คัดลอก')], db_index=True, max_length=32, verbose_name='event')),
                ('session_id', models.CharField(db_index=True, max_length=32, verbose_name='รหัสเซสชัน (สุ่ม ไม่ผูกตัวตน)')),
                ('draw_period', models.DateField(blank=True, db_index=True, null=True, verbose_name='งวดที่ event อยู่ในช่วง')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลา')),
            ],
            options={
                'verbose_name': 'event analytics',
                'verbose_name_plural': 'event analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at'], name='analytics_a_name_3ed2f9_idx')],
            },
        ),
    ]
