# Generated by Django 5.0.14 on 2025-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(db_index=True, unique=True, verbose_name='วันที่ออกรางวัล')),
                ('result_data', models.JSONField(verbose_name='ข้อมูลผลรางวัลจาก API')),
                ('source', models.CharField(default='GLO API', max_length=50, verbose_name='แหล่งข้อมูล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
            ],
            options={
                'verbose_name': 'ผลรางวัลหวย',
                'verbose_name_plural': 'ผลรางวัลหวย',
                'ordering': ['-draw_date'],
            },
        ),
        migrations.DeleteModel(
            name='LotteryDraw',
        ),
        migrations.AddIndex(
            model_name='lottoresult',
            index=models.Index(fields=['draw_date'], name='lottery_che_draw_da_05dbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='lottoresult',
            index=models.Index(fields=['created_at'], name='lottery_che_created_e1b9d7_idx'),
        ),
    ]
