# Generated by Django 4.2.11 on 2025-08-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_checker', '0002_lottoresult_delete_lotterydraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoresult',
            name='api_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL ของ API'),
        ),
        migrations.AddField(
            model_name='lottoresult',
            name='draw_period',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='งวดที่'),
        ),
        migrations.AddField(
            model_name='lottoresult',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ข้อมูลถูกต้อง'),
        ),
        migrations.AddField(
            model_name='lottoresult',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, verbose_name='ตรวจสอบล่าสุด'),
        ),
        migrations.AddField(
            model_name='lottoresult',
            name='raw_api_response',
            field=models.JSONField(default=dict, verbose_name='ข้อมูลดิบจาก API'),
        ),
        migrations.AddField(
            model_name='lottoresult',
            name='validation_errors',
            field=models.TextField(blank=True, default='', verbose_name='ข้อผิดพลาดในการตรวจสอบ'),
        ),
    ]
