# Generated by Django 4.2.11 on 2025-08-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อโมเดล')),
                ('version', models.CharField(max_length=20, verbose_name='เวอร์ชัน')),
                ('algorithm', models.CharField(choices=[('random_forest', 'Random Forest'), ('neural_network', 'Neural Network'), ('pattern_analysis', 'Pattern Analysis'), ('statistical', 'Statistical Model')], default='pattern_analysis', max_length=50, verbose_name='อัลกอริทึม')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='ความแม่นยำ (%)')),
                ('training_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เทรน')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('parameters', models.JSONField(default=dict, verbose_name='พารามิเตอร์')),
            ],
            options={
                'verbose_name': 'โมเดล AI',
                'verbose_name_plural': 'โมเดล AI',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='LuckyNumberPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ทำนาย')),
                ('for_draw_date', models.DateField(blank=True, null=True, verbose_name='สำหรับงวดวันที่')),
                ('two_digit_numbers', models.CharField(help_text='คั่นด้วยเครื่องหมายจุลภาค', max_length=200, verbose_name='เลข 2 ตัว')),
                ('three_digit_numbers', models.CharField(help_text='คั่นด้วยเครื่องหมายจุลภาค', max_length=200, verbose_name='เลข 3 ตัว')),
                ('overall_confidence', models.FloatField(default=50.0, verbose_name='ความมั่นใจรวม (%)')),
                ('prediction_details', models.JSONField(default=dict, verbose_name='รายละเอียดการทำนาย')),
                ('factors_used', models.JSONField(default=dict, verbose_name='ปัจจัยที่ใช้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('views', models.IntegerField(default=0, verbose_name='จำนวนคนดู')),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodel', verbose_name='โมเดลที่ใช้')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอทำนาย')),
            ],
            options={
                'verbose_name': 'การทำนายเลขเด็ด',
                'verbose_name_plural': 'การทำนายเลขเด็ด',
                'ordering': ['-prediction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อปัจจัย')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัส')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('weight', models.FloatField(default=1.0, verbose_name='น้ำหนัก')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
            ],
            options={
                'verbose_name': 'ปัจจัยการทำนาย',
                'verbose_name_plural': 'ปัจจัยการทำนาย',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ ดีมาก'), (4, '⭐⭐⭐⭐ ดี'), (3, '⭐⭐⭐ ปานกลาง'), (2, '⭐⭐ แย่'), (1, '⭐ แย่มาก')], verbose_name='คะแนน')),
                ('comment', models.TextField(blank=True, verbose_name='ความคิดเห็น')),
                ('is_winner', models.BooleanField(default=False, verbose_name='ถูกรางวัล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ให้คะแนนเมื่อ')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_engine.luckynumberprediction', verbose_name='การทำนาย')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ให้ฟีดแบ็ค')),
            ],
            options={
                'verbose_name': 'ฟีดแบ็ค',
                'verbose_name_plural': 'ฟีดแบ็ค',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_result', models.CharField(max_length=6, verbose_name='ผลที่ออกจริง')),
                ('actual_two_digit', models.CharField(max_length=2, verbose_name='2 ตัวที่ออก')),
                ('is_correct_first', models.BooleanField(default=False, verbose_name='ถูกรางวัลที่ 1')),
                ('is_correct_two_digit', models.BooleanField(default=False, verbose_name='ถูก 2 ตัว')),
                ('is_correct_three_digit', models.BooleanField(default=False, verbose_name='ถูก 3 ตัว')),
                ('checked_date', models.DateField(auto_now_add=True, verbose_name='วันที่ตรวจสอบ')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_records', to='ai_engine.luckynumberprediction', verbose_name='การทำนาย')),
            ],
            options={
                'verbose_name': 'ความแม่นยำการทำนาย',
                'verbose_name_plural': 'ความแม่นยำการทำนาย',
            },
        ),
    ]
