# Generated by Django 4.2.11 on 2025-08-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อโมเดล')),
                ('role', models.CharField(choices=[('journalist', 'Journalist AI - วิเคราะห์ข่าวและโซเชียลมีเดีย'), ('interpreter', 'Interpreter AI - ตีความฝันและโหราศาสตร์'), ('statistician', 'Statistician AI - วิเคราะห์สถิติและเทรนด์'), ('ensemble', 'Ensemble AI - รวมผลจากโมเดลทั้งหมด')], max_length=20, verbose_name='บทบาท')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('input_data_types', models.JSONField(default=list, verbose_name='ประเภทข้อมูลนำเข้า')),
                ('weight_in_ensemble', models.FloatField(default=1.0, verbose_name='น้ำหนักในการรวม')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
            ],
            options={
                'verbose_name': 'ประเภทโมเดล AI',
                'verbose_name_plural': 'ประเภทโมเดล AI',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อแหล่งข้อมูล')),
                ('source_type', models.CharField(choices=[('news', 'ข่าว'), ('social_media', 'โซเชียลมีเดีย'), ('dreams', 'ความฝัน'), ('statistics', 'สถิติ'), ('trends', 'เทรนด์'), ('astrology', 'โหราศาสตร์')], max_length=20, verbose_name='ประเภท')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API Endpoint')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('scraping_interval', models.IntegerField(default=6, verbose_name='ความถี่เก็บข้อมูล (ชั่วโมง)')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='เก็บข้อมูลล่าสุด')),
            ],
            options={
                'verbose_name': 'แหล่งข้อมูล',
                'verbose_name_plural': 'แหล่งข้อมูล',
            },
        ),
        migrations.CreateModel(
            name='EnsemblePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_two_digit', models.JSONField(verbose_name='เลข 2 ตัวสุดท้าย')),
                ('final_three_digit', models.JSONField(verbose_name='เลข 3 ตัวสุดท้าย')),
                ('overall_confidence', models.FloatField(verbose_name='ความมั่นใจรวม')),
                ('prediction_summary', models.TextField(verbose_name='สรุปการทำนาย')),
                ('model_contributions', models.JSONField(verbose_name='การมีส่วนร่วมของแต่ละโมเดล')),
                ('total_data_points', models.IntegerField(verbose_name='จำนวนข้อมูลที่ใช้')),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาทำนาย')),
                ('is_featured', models.BooleanField(default=False, verbose_name='แสดงในหน้าหลัก')),
                ('view_count', models.IntegerField(default=0, verbose_name='จำนวนผู้ดู')),
            ],
            options={
                'verbose_name': 'การทำนายรวมสุดท้าย',
                'verbose_name_plural': 'การทำนายรวมสุดท้าย',
                'ordering': ['-prediction_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PredictionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True, verbose_name='รหัสเซสชัน')),
                ('for_draw_date', models.DateField(verbose_name='สำหรับงวดวันที่')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='เริ่มต้นเมื่อ')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='สิ้นสุดเมื่อ')),
                ('data_collection_period_start', models.DateTimeField(verbose_name='เก็บข้อมูลตั้งแต่')),
                ('data_collection_period_end', models.DateTimeField(verbose_name='เก็บข้อมูลถึง')),
                ('status', models.CharField(choices=[('collecting_data', 'กำลังเก็บข้อมูล'), ('analyzing', 'กำลังวิเคราะห์'), ('completed', 'เสร็จสิ้น'), ('failed', 'ล้มเหลว'), ('locked', 'ล็อกแล้ว')], default='collecting_data', max_length=20, verbose_name='สถานะ')),
                ('total_data_sources', models.IntegerField(default=0, verbose_name='จำนวนแหล่งข้อมูล')),
                ('total_data_points', models.IntegerField(default=0, verbose_name='จำนวนข้อมูล')),
                ('processing_time_seconds', models.FloatField(blank=True, null=True, verbose_name='เวลาประมวลผล (วินาที)')),
            ],
            options={
                'verbose_name': 'เซสชันการทำนาย',
                'verbose_name_plural': 'เซสชันการทำนาย',
                'ordering': ['-start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='prediction',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='old_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_engine.luckynumberprediction', verbose_name='การทำนายแบบเก่า'),
        ),
        migrations.CreateModel(
            name='PredictionAccuracyTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_first_prize', models.CharField(blank=True, max_length=6, verbose_name='รางวัลที่ 1 ที่ออกจริง')),
                ('actual_last_two_digits', models.CharField(blank=True, max_length=2, verbose_name='เลข 2 ตัวท้ายที่ออกจริง')),
                ('actual_last_three_digits', models.CharField(blank=True, max_length=3, verbose_name='เลข 3 ตัวท้ายที่ออกจริง')),
                ('two_digit_accuracy', models.BooleanField(default=False, verbose_name='ทำนายเลข 2 ตัวถูก')),
                ('three_digit_accuracy', models.BooleanField(default=False, verbose_name='ทำนายเลข 3 ตัวถูก')),
                ('first_prize_accuracy', models.BooleanField(default=False, verbose_name='ทำนายรางวัลที่ 1 ถูก')),
                ('model_accuracies', models.JSONField(default=dict, verbose_name='ความแม่นยำของแต่ละโมเดล')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='ตรวจสอบเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ')),
                ('ensemble_prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_tracking', to='ai_engine.ensembleprediction', verbose_name='การทำนาย')),
            ],
            options={
                'verbose_name': 'การติดตามความแม่นยำ',
                'verbose_name_plural': 'การติดตามความแม่นยำ',
            },
        ),
        migrations.AddField(
            model_name='ensembleprediction',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ensemble_prediction', to='ai_engine.predictionsession', verbose_name='เซสชัน'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='model_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodeltype', verbose_name='ประเภทโมเดลใหม่'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='ensemble_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_engine.ensembleprediction', verbose_name='การทำนาย AI รวม'),
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_numbers', models.JSONField(verbose_name='เลขที่ทำนาย')),
                ('confidence_scores', models.JSONField(verbose_name='คะแนนความมั่นใจ')),
                ('reasoning', models.JSONField(verbose_name='เหตุผลการทำนาย')),
                ('input_data_summary', models.JSONField(verbose_name='สรุปข้อมูลนำเข้า')),
                ('data_sources_used', models.JSONField(verbose_name='แหล่งข้อมูลที่ใช้')),
                ('processing_time', models.FloatField(verbose_name='เวลาประมวลผล (วินาที)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_engine.aimodeltype', verbose_name='โมเดล')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_predictions', to='ai_engine.predictionsession', verbose_name='เซสชัน')),
            ],
            options={
                'verbose_name': 'ผลการทำนายของโมเดล',
                'verbose_name_plural': 'ผลการทำนายของโมเดล',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='DataIngestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.TextField(verbose_name='ข้อมูลดิบ')),
                ('processed_content', models.TextField(blank=True, verbose_name='ข้อมูลที่ประมวลผลแล้ว')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='หัวข้อ')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่เผยแพร่')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='ผู้เขียน')),
                ('extracted_numbers', models.JSONField(default=list, verbose_name='เลขที่สกัดได้')),
                ('keywords', models.JSONField(default=list, verbose_name='คำสำคัญ')),
                ('sentiment_score', models.FloatField(blank=True, null=True, verbose_name='คะแนนอารมณ์')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='คะแนนความเกี่ยวข้อง')),
                ('ingested_at', models.DateTimeField(auto_now_add=True, verbose_name='เก็บข้อมูลเมื่อ')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='ประมวลผลเมื่อ')),
                ('processing_status', models.CharField(choices=[('pending', 'รอประมวลผล'), ('processing', 'กำลังประมวลผล'), ('completed', 'เสร็จสิ้น'), ('failed', 'ล้มเหลว')], default='pending', max_length=20, verbose_name='สถานะการประมวลผล')),
                ('error_message', models.TextField(blank=True, verbose_name='ข้อความข้อผิดพลาด')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_records', to='ai_engine.datasource', verbose_name='แหล่งข้อมูล')),
            ],
            options={
                'verbose_name': 'บันทึกการเก็บข้อมูล',
                'verbose_name_plural': 'บันทึกการเก็บข้อมูล',
                'ordering': ['-ingested_at'],
                'indexes': [models.Index(fields=['data_source', '-ingested_at'], name='ai_engine_d_data_so_f6adf8_idx'), models.Index(fields=['processing_status', '-ingested_at'], name='ai_engine_d_process_6e040b_idx')],
            },
        ),
    ]
