# Generated by Django 4.2.13 on 2026-09-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aimodeltype_datasource_ensembleprediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='attribution',
            field=models.CharField(blank=True, max_length=200, verbose_name='ที่มา/เครดิต'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='category',
            field=models.CharField(choices=[('rss', 'RSS Feed'), ('category_page', 'หน้าหมวดหมู่ (fallback)'), ('api', 'API'), ('internal', 'ภายในระบบ')], default='rss', max_length=20, verbose_name='วิธีดึงข้อมูล'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='fetch_policy',
            field=models.JSONField(default=dict, verbose_name='นโยบายเก็บข้อมูล'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='key',
            field=models.SlugField(default='', unique=True, verbose_name='รหัสแหล่งข้อมูล'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='ข้อผิดพลาดล่าสุด'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ล้มเหลวล่าสุด'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='สำเร็จล่าสุด'),
        ),
    ]
