# Generated by Django 4.2.13 on 2026-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_datasource_attribution_datasource_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='key',
            field=models.SlugField(blank=True, default=None, help_text='ว่างได้สำหรับแหล่งที่เพิ่มเอง (NULL ไม่ชน unique); แถวทะเบียนต้องมี key', null=True, unique=True, verbose_name='รหัสแหล่งข้อมูล'),
        ),
    ]
