# Generated by Django 4.2.30 on 2026-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_alter_datasource_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='license_note',
            field=models.TextField(blank=True, default='', verbose_name='บันทึกสิทธิ์'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='license_status',
            field=models.CharField(choices=[('pending', 'รอตรวจ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=10, verbose_name='สถานะสิทธิ์เนื้อหา'),
        ),
    ]
