# Generated by Django 4.2.11 on 2025-08-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อข่าว')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('intro', models.TextField(max_length=500, verbose_name='คำนำ')),
                ('content', models.TextField(verbose_name='เนื้อหาข่าว')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='รูปภาพหลัก')),
                ('extracted_numbers', models.CharField(blank=True, help_text='เลขที่วิเคราะห์ได้จากข่าว คั่นด้วยเครื่องหมายจุลภาค', max_length=200, verbose_name='เลขที่ได้จากข่าว')),
                ('confidence_score', models.IntegerField(default=50, help_text='0-100', verbose_name='ความน่าเชื่อถือ (%)')),
                ('status', models.CharField(choices=[('draft', 'แบบร่าง'), ('published', 'เผยแพร่'), ('archived', 'เก็บถาวร')], default='draft', max_length=10, verbose_name='สถานะ')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่เผยแพร่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('views', models.IntegerField(default=0, verbose_name='จำนวนคนดู')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้เขียน')),
            ],
            options={
                'verbose_name': 'บทความข่าว',
                'verbose_name_plural': 'บทความข่าว',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
            ],
            options={
                'verbose_name': 'หมวดหมู่ข่าว',
                'verbose_name_plural': 'หมวดหมู่ข่าว',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='ชื่อ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('content', models.TextField(verbose_name='ความคิดเห็น')),
                ('suggested_numbers', models.CharField(blank=True, help_text='เลขที่คิดว่าจะออก', max_length=100, verbose_name='เลขที่แนะนำ')),
                ('is_approved', models.BooleanField(default=False, verbose_name='อนุมัติแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='แสดงความเห็นเมื่อ')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsarticle', verbose_name='บทความ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้แสดงความเห็น')),
            ],
            options={
                'verbose_name': 'ความคิดเห็น',
                'verbose_name_plural': 'ความคิดเห็น',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newscategory', verbose_name='หมวดหมู่'),
        ),
        migrations.CreateModel(
            name='LuckyNumberHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('temple', 'วัด/ศาลเจ้า'), ('tree', 'ต้นไม้ศักดิ์สิทธิ์'), ('dream', 'ความฝัน'), ('natural', 'ปรากฏการณ์ธรรมชาติ'), ('accident', 'อุบัติเหตุ'), ('other', 'อื่นๆ')], max_length=20, verbose_name='ประเภทแหล่งที่มา')),
                ('source_name', models.CharField(max_length=200, verbose_name='ชื่อแหล่งที่มา')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='สถานที่')),
                ('lucky_numbers', models.CharField(max_length=100, verbose_name='เลขเด็ด')),
                ('reason', models.TextField(blank=True, verbose_name='เหตุผล/ที่มา')),
                ('reliability_score', models.IntegerField(default=50, verbose_name='ความน่าเชื่อถือ (%)')),
                ('hint_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ได้เลข')),
                ('for_draw_date', models.DateField(blank=True, null=True, verbose_name='สำหรับงวดวันที่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lucky_hints', to='news.newsarticle', verbose_name='ข่าวที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'เลขเด็ด',
                'verbose_name_plural': 'เลขเด็ด',
                'ordering': ['-hint_date'],
            },
        ),
    ]
