# Generated by Django 5.0.14 on 2025-08-21 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Slug ต้องประกอบด้วยตัวอักษร ตัวเลข ขีดล่าง ขีดกลาง หรือตัวอักษรภาษาไทยเท่านั้น', regex='^[a-zA-Z0-9\\u0E00-\\u0E7F_-]+$')], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug ต้องประกอบด้วยตัวอักษร ตัวเลข ขีดล่าง ขีดกลาง หรือตัวอักษรภาษาไทยเท่านั้น', regex='^[a-zA-Z0-9\\u0E00-\\u0E7F_-]+$')], verbose_name='Slug'),
        ),
    ]
