# Generated by Django 4.2.11 on 2025-08-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_slug_alter_newscategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL แหล่งที่มา'),
        ),
    ]
