# Generated by Django 4.2.11 on 2025-09-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='lottery_category',
            field=models.CharField(blank=True, choices=[('accident', 'อุบัติเหตุ'), ('celebrity', 'คนดัง'), ('economic', 'เศรษฐกิจ'), ('general', 'ทั่วไป')], help_text='หมวดหมู่ที่วิเคราะห์โดยระบบใหม่', max_length=20, verbose_name='หมวดหมู่สำหรับหวย'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='lottery_relevance_score',
            field=models.IntegerField(default=0, help_text='0-100 คะแนนจากระบบวิเคราะห์ใหม่', verbose_name='คะแนนความเหมาะสมหวย'),
        ),
    ]
