# Generated by Django 4.2.11 on 2025-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_lottery_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='insight_analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วิเคราะห์ Insight-AI เมื่อ'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='insight_entities',
            field=models.JSONField(blank=True, default=list, verbose_name='เลขจาก Insight-AI'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='insight_impact_score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0', verbose_name='คะแนนผลกระทบ (Insight-AI)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='insight_summary',
            field=models.TextField(blank=True, verbose_name='สรุปเหตุการณ์ (Insight-AI)'),
        ),
    ]
