# Generated by Django 4.2.13 on 2025-09-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_insight_analyzed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='lottery_category',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='lottery_relevance_score',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='numbers_with_reasons',
            field=models.JSONField(blank=True, default=list, help_text="รูปแบบ: [{'number': '24', 'reason': 'วันที่เกิดเหตุ'}, ...]", verbose_name='เลขพร้อมเหตุผล'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='extracted_numbers',
            field=models.CharField(blank=True, help_text='เลขที่วิเคราะห์ได้จากข่าว คั่นด้วยเครื่องหมายจุลภาค', max_length=200, verbose_name='เลขที่ได้จากข่าว (เก่า)'),
        ),
    ]
