# Generated by Django 4.2.13 on 2025-09-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_add_numbers_with_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='extracted_numbers',
        ),
    ]
