# Generated by Django 4.2.13 on 2025-09-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_extracted_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='insight_analyzed_at',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='insight_entities',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='insight_impact_score',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='insight_summary',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='source_url',
        ),
    ]
