# Generated by Django 4.2.13 on 2026-09-11 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_alter_datasource_key'),
        ('news', '0008_remove_source_url_and_insight_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='analysis_error',
            field=models.TextField(blank=True, default='', verbose_name='ข้อผิดพลาดวิเคราะห์'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'รอวิเคราะห์'), ('analyzed', 'วิเคราะห์แล้ว'), ('failed', 'วิเคราะห์ล้มเหลว')], default='pending', max_length=10, verbose_name='สถานะวิเคราะห์'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='แฮชเนื้อหา (กันซ้ำ)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='ai_engine.datasource', verbose_name='แหล่งที่ดึงมา'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่ดึง'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL ต้นฉบับ'),
        ),
    ]
