# Generated by Django 4.2.11 on 2025-08-04 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
            ],
            options={
                'verbose_name': 'หมวดหมู่ความฝัน',
                'verbose_name_plural': 'หมวดหมู่ความฝัน',
            },
        ),
        migrations.CreateModel(
            name='DreamKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100, verbose_name='คำสำคัญ')),
                ('numbers', models.CharField(help_text='ใส่เลขคั่นด้วยเครื่องหมายจุลภาค เช่น 12,34,56', max_length=100, verbose_name='เลขที่เกี่ยวข้อง')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='dreams.dreamcategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'คำสำคัญความฝัน',
                'verbose_name_plural': 'คำสำคัญความฝัน',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='DreamInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_text', models.TextField(verbose_name='รายละเอียดความฝัน')),
                ('interpreted_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ตีความ')),
                ('keywords_found', models.TextField(blank=True, verbose_name='คำสำคัญที่พบ')),
                ('suggested_numbers', models.CharField(blank=True, max_length=200, verbose_name='เลขที่แนะนำ')),
                ('interpretation', models.TextField(blank=True, verbose_name='คำทำนาย')),
                ('dream_date', models.DateField(blank=True, null=True, verbose_name='วันที่ฝัน')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'การตีความฝัน',
                'verbose_name_plural': 'การตีความฝัน',
                'ordering': ['-interpreted_at'],
            },
        ),
    ]
