# Generated by Django 5.0.14 on 2025-08-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreaminterpretation',
            name='dream_date',
        ),
    ]
