# Generated by Django 4.2.11 on 2025-08-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_add_main_secondary_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreaminterpretation',
            name='main_symbols',
            field=models.TextField(blank=True, help_text='สัญลักษณ์หลักที่พบในความฝัน', verbose_name='สัญลักษณ์หลัก'),
        ),
        migrations.AddField(
            model_name='dreaminterpretation',
            name='predicted_numbers_json',
            field=models.JSONField(blank=True, help_text='เก็บผลลัพธ์ทั้งหมดจาก Seer-AI', null=True, verbose_name='ผลลัพธ์การทำนาย (JSON)'),
        ),
        migrations.AddField(
            model_name='dreaminterpretation',
            name='sentiment',
            field=models.CharField(blank=True, help_text='Positive, Negative, or Neutral', max_length=20, verbose_name='อารมณ์ของความฝัน'),
        ),
        migrations.AlterField(
            model_name='dreaminterpretation',
            name='keywords_found',
            field=models.TextField(blank=True, verbose_name='คำสำคัญที่พบ (Legacy)'),
        ),
        migrations.AlterField(
            model_name='dreaminterpretation',
            name='suggested_numbers',
            field=models.CharField(blank=True, max_length=200, verbose_name='เลขที่แนะนำ (Legacy)'),
        ),
    ]
