# Generated by Django 4.2.11 on 2025-08-26 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_alter_newsarticle_slug_alter_newscategory_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('temple', 'วัด'), ('shrine', 'ศาลเจ้า'), ('sacred_tree', 'ต้นไม้ศักดิ์สิทธิ์'), ('naga', 'พญานาค'), ('mysterious', 'สิ่งลี้ลับ'), ('cave', 'ถ้ำ'), ('mountain', 'ภูเขา'), ('river', 'แม่น้ำ/ลำธาร'), ('other', 'อื่นๆ')], max_length=50, unique=True, verbose_name='ประเภทสถานที่')),
                ('icon', models.CharField(blank=True, help_text='CSS class หรือ URL ของไอคอน', max_length=100, verbose_name='ไอคอน')),
            ],
            options={
                'verbose_name': 'ประเภทสถานที่',
                'verbose_name_plural': 'ประเภทสถานที่',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('north', 'ภาคเหนือ'), ('central', 'ภาคกลาง'), ('northeast', 'ภาคอีสาน'), ('south', 'ภาคใต้'), ('east', 'ภาคตะวันออก'), ('west', 'ภาคตะวันตก')], max_length=20, unique=True, verbose_name='ภาค')),
            ],
            options={
                'verbose_name': 'ภาค',
                'verbose_name_plural': 'ภาค',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='จังหวัด')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucky_spots.region', verbose_name='ภาค')),
            ],
            options={
                'verbose_name': 'จังหวัด',
                'verbose_name_plural': 'จังหวัด',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LuckyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสถานที่')),
                ('description', models.TextField(help_text='ประวัติความเป็นมา ความเชื่อ เรื่องราวที่น่าสนใจ', verbose_name='รายละเอียด')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='ละติจูด')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='ลองจิจูด')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('lucky_numbers', models.TextField(blank=True, help_text='เลขเด็ดที่เคยออกจากสถานที่นี้ (แยกด้วยเครื่องหมายจุลภาค)', verbose_name='เลขเด็ดที่เคยให้โชค')),
                ('highlights', models.TextField(blank=True, help_text='สรุปจุดเด่นของสถานที่', verbose_name='ไฮไลท์สำคัญ')),
                ('main_image', models.ImageField(blank=True, upload_to='lucky_spots/main/', verbose_name='รูปภาพหลัก')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนการเข้าชม')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucky_spots.locationcategory', verbose_name='ประเภท')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucky_spots.province', verbose_name='จังหวัด')),
            ],
            options={
                'verbose_name': 'สถานที่เลขเด็ด',
                'verbose_name_plural': 'สถานที่เลขเด็ด',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationNewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_tags', to='lucky_spots.luckylocation', verbose_name='สถานที่')),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle', verbose_name='ข่าว')),
            ],
            options={
                'verbose_name': 'แท็กข่าวสถานที่',
                'verbose_name_plural': 'แท็กข่าวสถานที่',
            },
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lucky_spots/gallery/', verbose_name='รูปภาพ')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='คำอธิบายรูป')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='lucky_spots.luckylocation', verbose_name='สถานที่')),
            ],
            options={
                'verbose_name': 'รูปภาพสถานที่',
                'verbose_name_plural': 'รูปภาพสถานที่',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LocationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='สำหรับผู้ใช้ที่ไม่ได้ลงทะเบียน', max_length=100, verbose_name='ชื่อ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('comment', models.TextField(verbose_name='ความคิดเห็น')),
                ('lucky_number_shared', models.CharField(blank=True, max_length=100, verbose_name='เลขเด็ดที่แบ่งปัน')),
                ('is_approved', models.BooleanField(default=False, verbose_name='อนุมัติแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lucky_spots.luckylocation', verbose_name='สถานที่')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ความคิดเห็น',
                'verbose_name_plural': 'ความคิดเห็น',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='luckylocation',
            index=models.Index(fields=['province'], name='lucky_spots_provinc_c15c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='luckylocation',
            index=models.Index(fields=['category'], name='lucky_spots_categor_7ee0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='luckylocation',
            index=models.Index(fields=['is_active'], name='lucky_spots_is_acti_7aa1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='luckylocation',
            index=models.Index(fields=['latitude', 'longitude'], name='lucky_spots_latitud_3306d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationnewstag',
            unique_together={('location', 'news_article')},
        ),
    ]
