# Generated by Django 5.2.6 on 2025-09-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสูตร')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('method', models.TextField(verbose_name='วิธีการคำนวณ')),
                ('accuracy_rate', models.FloatField(verbose_name='อัตราความแม่นยำ')),
                ('total_predictions', models.IntegerField(default=0, verbose_name='จำนวนการทำนาย')),
                ('correct_predictions', models.IntegerField(default=0, verbose_name='การทำนายที่ถูก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'สูตรคำนวณ',
                'verbose_name_plural': 'สูตรคำนวณ',
            },
        ),
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(verbose_name='วันที่ออกรางวัล')),
                ('winning_numbers', models.CharField(max_length=20, verbose_name='เลขที่ออก')),
                ('first_prize', models.CharField(max_length=6, verbose_name='รางวัลที่ 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ผลการออกรางวัล',
                'verbose_name_plural': 'ผลการออกรางวัล',
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_numbers', models.CharField(max_length=20, verbose_name='เลขที่ทำนาย')),
                ('draw_date', models.DateField(verbose_name='งวดที่ทำนาย')),
                ('is_correct', models.BooleanField(default=False, verbose_name='ถูกต้อง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto_formula.lotteryformula')),
            ],
            options={
                'verbose_name': 'การทำนาย',
                'verbose_name_plural': 'การทำนาย',
            },
        ),
    ]
