# Generated by Django 4.2.13 on 2026-09-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_formula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryformula',
            name='code',
            field=models.SlugField(default='', unique=True, verbose_name='รหัสสูตร'),
        ),
        migrations.AddField(
            model_name='lotteryformula',
            name='input_spec',
            field=models.JSONField(default=dict, verbose_name='สเปก input'),
        ),
        migrations.AddField(
            model_name='lotteryformula',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True, verbose_name='อนุมัติใช้งาน'),
        ),
        migrations.AddField(
            model_name='lotteryformula',
            name='output_spec',
            field=models.JSONField(default=dict, verbose_name='สเปก output'),
        ),
        migrations.AddField(
            model_name='lotteryformula',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='เวอร์ชันสูตร'),
        ),
    ]
