# Generated by Django 4.2.13 on 2026-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_formula', '0002_lotteryformula_code_lotteryformula_input_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryformula',
            name='verified_count',
            field=models.IntegerField(default=0, verbose_name='จำนวนที่ตรวจผลแล้วย้อนหลัง'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='input_numbers',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='เลขอ้างอิงที่ใช้คำนวณ'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ตรวจเมื่อ'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='is_correct',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='ถูกต้อง'),
        ),
    ]
