# Generated by Django 4.2.11 on 2025-08-04 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotColdNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่คำนวณ')),
                ('hot_2d', models.JSONField(default=list, verbose_name='เลขฮอต 2 ตัว')),
                ('hot_3d', models.JSONField(default=list, verbose_name='เลขฮอต 3 ตัว')),
                ('cold_2d', models.JSONField(default=list, verbose_name='เลขเย็น 2 ตัว')),
                ('cold_3d', models.JSONField(default=list, verbose_name='เลขเย็น 3 ตัว')),
                ('calculation_days', models.IntegerField(default=90, verbose_name='จำนวนวันที่ใช้คำนวณ')),
            ],
            options={
                'verbose_name': 'เลขฮอต/เลขเย็น',
                'verbose_name_plural': 'เลขฮอต/เลขเย็น',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(unique=True, verbose_name='วันที่ออกรางวัล')),
                ('draw_round', models.CharField(blank=True, max_length=20, verbose_name='งวดที่')),
                ('first_prize', models.CharField(max_length=6, verbose_name='รางวัลที่ 1')),
                ('two_digit', models.CharField(max_length=2, verbose_name='เลขท้าย 2 ตัว')),
                ('three_digit_front', models.CharField(help_text='คั่นด้วยเครื่องหมายจุลภาค', max_length=100, verbose_name='เลขหน้า 3 ตัว')),
                ('three_digit_back', models.CharField(help_text='คั่นด้วยเครื่องหมายจุลภาค', max_length=100, verbose_name='เลขท้าย 3 ตัว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ')),
            ],
            options={
                'verbose_name': 'ผลการออกรางวัล',
                'verbose_name_plural': 'ผลการออกรางวัล',
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='NumberStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, unique=True, verbose_name='เลข')),
                ('number_type', models.CharField(choices=[('2D', 'เลข 2 ตัว'), ('3D', 'เลข 3 ตัว')], max_length=10, verbose_name='ประเภท')),
                ('total_appearances', models.IntegerField(default=0, verbose_name='จำนวนครั้งที่ออก')),
                ('last_appeared', models.DateField(blank=True, null=True, verbose_name='ออกล่าสุดเมื่อ')),
                ('days_since_last', models.IntegerField(default=0, verbose_name='จำนวนวันที่ไม่ออก')),
                ('max_consecutive', models.IntegerField(default=0, verbose_name='ออกติดต่อกันสูงสุด')),
                ('average_gap', models.FloatField(default=0, verbose_name='ระยะห่างเฉลี่ย (วัน)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
            ],
            options={
                'verbose_name': 'สถิติเลข',
                'verbose_name_plural': 'สถิติเลข',
                'ordering': ['-total_appearances'],
            },
        ),
    ]
