# Generated by Django 4.2.30 on 2026-09-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('contact', 'ติดต่อทั่วไป'), ('report', 'แจ้งเนื้อหาไม่เหมาะสม'), ('removal', 'ขอลบข้อมูล')], default='contact', max_length=10, verbose_name='ประเภท')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='ชื่อ')),
                ('contact', models.CharField(blank=True, max_length=254, verbose_name='ช่องทางติดต่อกลับ')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('status', models.CharField(choices=[('new', 'ใหม่'), ('read', 'อ่านแล้ว'), ('done', 'ดำเนินการแล้ว')], default='new', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ส่งเมื่อ')),
            ],
            options={
                'verbose_name': 'ข้อความติดต่อ',
                'verbose_name_plural': 'ข้อความติดต่อ',
                'ordering': ['-created_at'],
            },
        ),
    ]
