# Generated by Django 4.2.30 on 2026-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('contact', 'ติดต่อทั่วไป'), ('report', 'แจ้งเนื้อหาไม่เหมาะสม'), ('removal', 'ขอลบข้อมูล'), ('beta', 'ข้อเสนอแนะช่วง beta')], default='contact', max_length=10, verbose_name='ประเภท'),
        ),
    ]
