# Generated by Django 4.2.30 on 2026-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='รหัสงาน')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='ชื่องาน')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='ผู้รับผิดชอบ')),
                ('status', models.CharField(choices=[('idle', 'ยังไม่เคยรัน'), ('running', 'กำลังรัน'), ('success', 'สำเร็จ'), ('failed', 'ล้มเหลว'), ('skipped', 'ข้าม')], default='idle', max_length=10, verbose_name='สถานะล่าสุด')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='รันล่าสุด')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='สำเร็จล่าสุด')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='ข้อผิดพลาดล่าสุด')),
                ('consecutive_failures', models.IntegerField(default=0, verbose_name='ล้มเหลวติดกัน')),
                ('attempts_left', models.IntegerField(default=0, verbose_name='ครั้งลองซ้ำที่เหลือ')),
                ('next_run_at', models.DateTimeField(blank=True, help_text='None = ถึงกำหนดทันที', null=True, verbose_name='รอบถัดไป')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='ล็อกเมื่อ')),
                ('last_duration_seconds', models.FloatField(blank=True, null=True, verbose_name='ใช้เวลารอบล่าสุด (วินาที)')),
            ],
            options={
                'verbose_name': 'งานตามตาราง',
                'verbose_name_plural': 'งานตามตาราง',
            },
        ),
    ]
