# Generated by Django 4.2.30 on 2026-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='รหัสเชิญ')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='หมายเหตุ/กลุ่มผู้ใช้')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = ไม่จำกัด', verbose_name='จำนวนใช้สูงสุด')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='ใช้ไปแล้ว')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='ใช้ล่าสุด')),
            ],
            options={
                'verbose_name': 'รหัสเชิญ beta',
                'verbose_name_plural': 'รหัสเชิญ beta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='รหัสเหตุการณ์')),
                ('level', models.CharField(choices=[('P0', 'P0 — หยุด rollout ทันที'), ('P1', 'P1 — เฝ้าระวัง'), ('P2', 'P2 — บันทึกไว้')], default='P1', max_length=2, verbose_name='ระดับ')),
                ('message', models.CharField(max_length=300, verbose_name='ข้อความประกาศ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ยังไม่ปิดเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เปิดเมื่อ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='ปิดเมื่อ')),
            ],
            options={
                'verbose_name': 'ธงเหตุการณ์',
                'verbose_name_plural': 'ธงเหตุการณ์',
                'ordering': ['-created_at'],
            },
        ),
    ]
